/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as ChangePasswordRouteImport } from './app/routes/change-password'
import { Route as LegalRouteImport } from './app/routes/legal'
import { Route as NewRouteImport } from './app/routes/new'
import { Route as SignInRouteImport } from './app/routes/sign-in'
import { Route as SignUpRouteImport } from './app/routes/sign-up'
import { Route as SuccessRouteImport } from './app/routes/success'
import { Route as AccountIndexRouteImport } from './app/routes/account/index'
import { Route as AccountSubscriptionRouteImport } from './app/routes/account/subscription'
import { Route as FIdRouteImport } from './app/routes/f.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSubscriptionRoute = AccountSubscriptionRouteImport.update({
  id: '/account/subscription',
  path: '/account/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const FIdRoute = FIdRouteImport.update({
  id: '/f/$id',
  path: '/f/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/legal': typeof LegalRoute
  '/new': typeof NewRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/success': typeof SuccessRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/f/$id': typeof FIdRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/legal': typeof LegalRoute
  '/new': typeof NewRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/success': typeof SuccessRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/f/$id': typeof FIdRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/legal': typeof LegalRoute
  '/new': typeof NewRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/success': typeof SuccessRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/f/$id': typeof FIdRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/legal'
    | '/new'
    | '/sign-in'
    | '/sign-up'
    | '/success'
    | '/account/subscription'
    | '/f/$id'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/legal'
    | '/new'
    | '/sign-in'
    | '/sign-up'
    | '/success'
    | '/account/subscription'
    | '/f/$id'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/legal'
    | '/new'
    | '/sign-in'
    | '/sign-up'
    | '/success'
    | '/account/subscription'
    | '/f/$id'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LegalRoute: typeof LegalRoute
  NewRoute: typeof NewRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SuccessRoute: typeof SuccessRoute
  AccountSubscriptionRoute: typeof AccountSubscriptionRoute
  FIdRoute: typeof FIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/subscription': {
      id: '/account/subscription'
      path: '/account/subscription'
      fullPath: '/account/subscription'
      preLoaderRoute: typeof AccountSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$id': {
      id: '/f/$id'
      path: '/f/$id'
      fullPath: '/f/$id'
      preLoaderRoute: typeof FIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LegalRoute: LegalRoute,
  NewRoute: NewRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SuccessRoute: SuccessRoute,
  AccountSubscriptionRoute: AccountSubscriptionRoute,
  FIdRoute: FIdRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
